### ISSUE TITLE
Bezel HUD breaks B61?

### ISSUE THREAD

**Issue by daz** [bencochran/bezelhud#16]
After updating to B61, QS wouldn't open. I deleted it from /Applications and manually downloaded QS, changed the interface to default Bezel, works fine. Every time I change it to Bezel HUD it kill QS and I need to redownload (there's probably a better way to reset it but redownloading works).

**Comment by daz** [comment]
Removed Bezel HUD and reinstalled. Fixed it.

**Comment by bencochran** [comment]
You’re correct, though it’s kind of the other way around. Basically BezelHUD breaks on each new QS release. Read about [fragile base classes](http://en.wikipedia.org/wiki/Fragile_base_class) for more info on why. So BezelHUD has to be rebuilt each time QS is updated.

Hopefully the core QS team will convert the project to 64-bit soon which will [eliminate the issue](http://en.wikipedia.org/wiki/Objective-C#Non-fragile_instance_variables).

**Comment by bencochran** [comment]
Also, forgot to say: sorry for the hassle. Thanks for reporting it  :)

**Comment by daz** [comment]
Keep up the good work :)
