### ISSUE TITLE
BezelHUD stops working with 1.2.0 (400D)

### ISSUE THREAD

**Issue by mankoff** [bencochran/bezelhud#19]
QuickSilver just auto-updated to 1.2.0 (400D) and BezelHUD has stopped working. The interface is now the default classic bezel. Re-installing doesn't seem to help.

**Comment by griffin-stewie** [comment]
+1

**Comment by dalemanthei** [comment]
error: Error Domain=NSCocoaErrorDomain Code=3588 "The bundle “BezelHUD” couldn’t be loaded." UserInfo=0x61800047b280 {NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle.

I tried clearing the caches and reinstalling bezelhud but no joy.

OS X 10.9.5 (13F34)
Quicksilver 1.2.0 (400F)

**Comment by timvisher** [comment]
FWIW, the BezelHUD is largely reproducible by messing with the built-in Bezel theme. I was sad about this when it went but then I spent a little time and basically reproduced it.
