### ISSUE TITLE
centre

### ISSUE THREAD

**Issue by okdana** [bencochran/bezelhud#3]
Hi, small but annoying issue: BezelHUD does not appear in the centre of my screen when i invoke it -- it's too close to the top and about 20 pixels to the left of centre. This makes me go all OCD-crazy, you know?

I've tried editing the NIB to see if that'd fix it, but the 'initial position' thing didn't seem to have any effect, so i don't know.

Could you please make it so that BezelHUD appears closer to the centre of the screen, the same way the original Bezel plug-in does? I would say it should be half-way from the sides (exact horizontal centre) and maybe 3/5 the way from the bottom (a little bit higher than exact vertical centre). Something like this:

```
--------------------------
--------------------------
----------||||||----------
--------------------------
--------------------------
--------------------------
```

OS X 10.6
iMac7,1
1920x1200 resolution
Quicksilver ß56a7
BezelHUD 1.2a2

Thanks!

**Comment by bencochran** [comment]
Unlike Bezel, BezelHUD can be repositioned on the screen. Try grabbing the titlebar and positioning it where you'd like it.

I've contemplated adding an option to make it stuck to the center of the screen like Bezel, as mine always seems a little off-center.

But in the meantime, you should be able to put it in an acceptable position.

**Comment by okdana** [comment]
That is the work-around i'm using for the time being, but i do think it's a _work-around_, not a solution, for a few reasons:
1. In order to position it in the middle of the screen i have to do something tricky like make a desktop background in Photoshop with a BezelHUD-sized rectangle in the middle and then line them both up. I don't (unfortunately) have the ability to determine the exact centre just with my eyes, and anything less will be the same problem as before.
2. Since, as you said, BezelHUD _can_ be repositioned on the screen, this means that if i ever accidentally move it (which is very possible) i have to go through # 1 again. (I think something like QuickTime X's behaviour would be appropriate here — the control is moveable, but it goes back to the default position when you start a new session.)
3. I haven't actually tried, because i don't want to mess up the settings i've already got, but i think if i ever change to a different appearance plug-in i lose my position?

Sorry if this seems like an over-reaction to a small thing, i just can't help it. :/

cheers
