### ISSUE TITLE
last selected path ...

### ISSUE THREAD

**Issue by calc** [bencochran/bezelhud#6]
.... remains showing at the bottom of the bezel hud window till the next time I select an object. Can QS be made to 'forget' the path after a period of inactivity/ delete is pressed a certain number of times?

**Comment by jeffcox** [comment]
This is what calc is referring to: http://imgur.com/eeq5G.png

If the search field is blank the text along the bottom describing the selected item should be equally blank, instead it shows the description of the last item selected.  The only time that area is appropriately clear is when QS first starts.

**Comment by skurfer** [comment]
I was going to report an issue with proxy objects, but this is probably the same thing.

If you bring up a proxy object, like Current Selection or Latest Download (coming in B59), the text at the bottom refers to whatever was up just before the proxy was matched.
