### ISSUE TITLE
BezelHUB causing QS crash on launch

### ISSUE THREAD

**Issue by bencochran** [bencochran/bezelhud#7]
As reported here:

http://twitter.com/yagoabascal/status/6349828611
http://twitter.com/yagoabascal/status/6353322308
http://twitter.com/yagoabascal/status/6353909338

With the following crash log:

```
05/12/09 05  1:03:53    Quicksilver[5079]   [Quicksilver -[NSApplication(Info) wasLaunchedAtLogin]]: parentProcessInfoDict = '"IsHiddenAttr" = 0;
"LSCheckInTime*" = 2009-12-03 15:57:55 +0100;
"LSBackgroundOnly" = 0;
"FileCreator" = "MACS";
"CFBundleIdentifier" = "com.apple.finder";
"LSSystemWillDisplayDeathNotification" = 0;
"Attributes" = 4096;
"CFBundleExecutable" = "/System/Library/CoreServices/Finder.app/Contents/MacOS/Finder";
"LSUIPresentationMode" = 0;
"IsCheckedInAttr" = 1;
"PSN" = 28679;
"LSUIElement" = 0;
"CFBundleName" = "Finder";
"CFBundleVersion" = 274890752;
"BundlePath" = "/System/Library/CoreServices/Finder.app";
"pid" = 681;
"FileType" = "FNDR";
"Flavor" = 3;
'
05/12/09 05  1:03:53    Quicksilver[5079]   [Quicksilver -[NSApplication(Info) wasLaunchedAtLogin]]: parentProcessInfoDict = '"IsHiddenAttr" = 0;
"LSCheckInTime*" = 2009-12-03 15:57:55 +0100;
"LSBackgroundOnly" = 0;
"FileCreator" = "MACS";
"CFBundleIdentifier" = "com.apple.finder";
"LSSystemWillDisplayDeathNotification" = 0;
"Attributes" = 4096;
"CFBundleExecutable" = "/System/Library/CoreServices/Finder.app/Contents/MacOS/Finder";
"LSUIPresentationMode" = 0;
"IsCheckedInAttr" = 1;
"PSN" = 28679;
"LSUIElement" = 0;
"CFBundleName" = "Finder";
"CFBundleVersion" = 274890752;
"BundlePath" = "/System/Library/CoreServices/Finder.app";
"pid" = 681;
"FileType" = "FNDR";
"Flavor" = 3;
'
05/12/09 05  1:04:01    [0x0-0x380380].com.blacktree.Quicksilver[5079]  objc[5079]: Class QSIconLoader is implemented in both /Applications/Quicksilver.app/Contents/MacOS/../Frameworks/QSCore.framework/Versions/A/QSCore and /Users/Yago/Library/Application Support/Quicksilver/PlugIns/BezelHUD.qsplugin/Contents/MacOS/BezelHUD. One of the two will be used. Which one is undefined.
05/12/09 05  1:04:01    [0x0-0x380380].com.blacktree.Quicksilver[5079]  objc[5079]: Class QSCollectingSearchObjectView is implemented in both /Applications/Quicksilver.app/Contents/MacOS/../Frameworks/QSInterface.framework/Versions/A/QSInterface and /Users/Yago/Library/Application Support/Quicksilver/PlugIns/BezelHUD.qsplugin/Contents/MacOS/BezelHUD. One of the two will be used. Which one is undefined.
05/12/09 05  1:04:01    [0x0-0x380380].com.blacktree.Quicksilver[5079]  objc[5079]: Class QSTableView is implemented in both /Applications/Quicksilver.app/Contents/MacOS/../Frameworks/QSInterface.framework/Versions/A/QSInterface and /Users/Yago/Library/Application Support/Quicksilver/PlugIns/BezelHUD.qsplugin/Contents/MacOS/BezelHUD. One of the two will be used. Which one is undefined.
05/12/09 05  1:04:01    [0x0-0x380380].com.blacktree.Quicksilver[5079]  objc[5079]: Class QSResultWindow is implemented in both /Applications/Quicksilver.app/Contents/MacOS/../Frameworks/QSInterface.framework/Versions/A/QSInterface and /Users/Yago/Library/Application Support/Quicksilver/PlugIns/BezelHUD.qsplugin/Contents/MacOS/BezelHUD. One of the two will be used. Which one is undefined.
05/12/09 05  1:04:01    Quicksilver[5079]   -[SFResults count]: unrecognized selector sent to instance 0x1439d290
05/12/09 05  1:04:01    Quicksilver[5079]   -[SFResults count]: unrecognized selector sent to instance 0x1439d290
05/12/09 05  1:04:18    Quicksilver[5079]   -[SFResults count]: unrecognized selector sent to instance 0x1439d290
05/12/09 05  1:04:19    Quicksilver[5079]   HIToolbox: ignoring exception '-[SFResults count]: unrecognized selector sent to instance 0x1439d290' that raised inside Carbon event dispatch
(
        0   CoreFoundation                      0x975b540a __raiseError + 410
        1   libobjc.A.dylib                     0x934ef509 objc_exception_throw + 56
        2   CoreFoundation                      0x9760190b -[NSObject(NSObject) doesNotRecognizeSelector:] + 187
        3   CoreFoundation                      0x9755cdb6 ___forwarding___ + 950
        4   CoreFoundation                      0x9755c982 _CF_forwarding_prep_0 + 50
        5   QSInterface                         0x0018ee8c -[QSCollectingSearchObjectView objectValue] + 60
        6   QSInterface                         0x0019e5f6 -[QSInterfaceController activate:] + 406
        7   Quicksilver                         0x0000be39 -[QSController activateInterface:] + 217
        8   QSFoundation                        0x00067a6d -[NDHotKeyEvent performHotKeyPressed] + 333
        9   QSFoundation                        0x000655d0 eventHandlerCallback + 624
        10  HIToolbox                           0x968a4e29 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1567
        11  HIToolbox                           0x968a40f0 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 411
        12  HIToolbox                           0x968c6981 SendEventToEventTarget + 52
        13  AppKit                              0x986f7f56 -[NSApplication sendEvent:] + 7494
        14  Quicksilver                         0x00004195 -[QSApp sendEvent:] + 1685
        15  AppKit                              0x9868b4ff -[NSApplication run] + 917
        16  AppKit                              0x98683535 NSApplicationMain + 574
        17  Quicksilver                         0x0001ef30 main + 240
        18  Quicksilver                         0x00002fe6 start + 54
)
05/12/09 05  1:04:19    Quicksilver[5079]   -[SFResults count]: unrecognized selector sent to instance 0x1439d290
05/12/09 05  1:04:19    Quicksilver[5079]   -[SFResults count]: unrecognized selector sent to instance 0x1439d290
```

**Comment by pjrobertson** [comment]
I can also confirm this isn't working for me with ß58 or (soon to be released ß59)

Crash logs:

Process:         Quicksilver [62512]
Path:            /Applications/Quicksilver.app/Contents/MacOS/Quicksilver
Identifier:      com.blacktree.Quicksilver
Version:         ß58 (3841)
Code Type:       X86 (Native)
Parent Process:  ??? [1]

Date/Time:       2011-04-14 09:01:54.334 +1000
OS Version:      Mac OS X 10.6.7 (10J869)
Report Version:  6

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x0000000000000001
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Application Specific Information:
objc_msgSend() selector name: window

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib                 0x942aced4 objc_msgSend + 20
1   ...cktree.Quicksilver.BezelHUD  0x129da09d -[BHCollectingSearchView showResultView:] + 125
2   com.blacktree.QSInterface       0x00125dd3 -[QSSearchObjectView performSearchFor:from:] + 1146
3   ???                             0x00232130 0 + 2302256

Thread 1:  Dispatch queue: com.apple.libdispatch-manager
0   libSystem.B.dylib               0x9040f922 kevent + 10
1   libSystem.B.dylib               0x9041003c _dispatch_mgr_invoke + 215
2   libSystem.B.dylib               0x9040f4f9 _dispatch_queue_invoke + 163
3   libSystem.B.dylib               0x9040f29e _dispatch_worker_thread2 + 240
4   libSystem.B.dylib               0x9040ed21 _pthread_wqthread + 390
5   libSystem.B.dylib               0x9040eb66 start_wqthread + 30

Thread 2:
0   libSystem.B.dylib               0x9040e9b2 __workq_kernreturn + 10
1   libSystem.B.dylib               0x9040ef48 _pthread_wqthread + 941
2   libSystem.B.dylib               0x9040eb66 start_wqthread + 30

Thread 3:
0   libSystem.B.dylib               0x9040f922 kevent + 10
1   com.blacktree.QSCore            0x000ccc8d -[UKKQueue watcherThread:] + 284
2   com.apple.Foundation            0x943e1a80 **NSThread__main** + 1499
3   libSystem.B.dylib               0x904167fd _pthread_start + 345
4   libSystem.B.dylib               0x90416682 thread_start + 34

Thread 4:
0   libSystem.B.dylib               0x903e909a mach_msg_trap + 10
1   libSystem.B.dylib               0x903e9807 mach_msg + 68
2   com.apple.CoreFoundation        0x9768937f **CFRunLoopRun + 2079
3   com.apple.CoreFoundation        0x97688464 CFRunLoopRunSpecific + 452
4   com.apple.CoreFoundation        0x97688291 CFRunLoopRunInMode + 97
5   com.apple.Foundation            0x9441a6f4 +[NSURLConnection(NSURLConnectionReallyInternal) _resourceLoadLoop:] + 329
6   com.apple.Foundation            0x943e1ad0 -[NSThread main] + 45
7   com.apple.Foundation            0x943e1a80 __NSThread__main** + 1499
8   libSystem.B.dylib               0x904167fd _pthread_start + 345
9   libSystem.B.dylib               0x90416682 thread_start + 34

Thread 5:
0   libSystem.B.dylib               0x9040e9b2 __workq_kernreturn + 10
1   libSystem.B.dylib               0x9040ef48 _pthread_wqthread + 941
2   libSystem.B.dylib               0x9040eb66 start_wqthread + 30

Thread 0 crashed with X86 Thread State (32-bit):
  eax: 0x00000001  ebx: 0x14293950  ecx: 0x94e8f7dc  edx: 0x00000000
  edi: 0x14255f70  esi: 0x129da031  ebp: 0xbfffe7d8  esp: 0xbfffe6ec
   ss: 0x0000001f  efl: 0x00010202  eip: 0x942aced4   cs: 0x00000017
   ds: 0x0000001f   es: 0x0000001f   fs: 0x00000000   gs: 0x00000037
  cr2: 0x00000001

**Comment by bencochran** [comment]
I believe I solved the issue you’re describing, Patrick. Pretty much just a recompile against updated QS and a few tweaks took care of it (as far as I can reproduce).

**Comment by pjrobertson** [comment]
Have you got a pathced plugin available for download? The one I have at qsapp.com/plugins doesn't work, or the one at http://code.bencochran.com/bezelhud/

I'll add a new one to the plugins repo if all's good :)

**Comment by pjrobertson** [comment]
... just seen and approved your qs---development post.

Will take it for a spin, even though I don't use it :)

**Comment by bencochran** [comment]
I just sent a test build to the Quicksilver Developers list. Or you can check it out here:

http://bencochran.com/dropbox/BezelHUD-20110413.zip

Let me know if it solves the issue for you.

**Comment by pjrobertson** [comment]
Fixed for me :)

I'll let the original tweeter who brought this up know, and he can test
since it's his primary interface

**Comment by bencochran** [comment]
Awesome. Thank you!
